[package]
name = "find-duplicate-files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
ring = "0.16.20"
data-encoding = "2.3.2"
